//! Schema migrations for the desktop SQLite database.
//!
//! The SQL is generated by drizzle-kit into `packages/db/migrations/*.sql` and embedded at build
//! time by `build.rs` (see `$OUT_DIR/migrations.rs`). Files are numbered from 1 in name order.
//!
//! Who applies them is a deliberate choice. `packages/db` ships the same SQL as `MIGRATIONS` and its
//! Tauri executor applies it through `applyMigrations` with a `_migrations` bookkeeping table, the
//! same path the web and node executors use. Registering the files here as well would run every
//! `CREATE TABLE` twice (the plugin keeps its own `_sqlx_migrations` table and knows nothing about
//! `_migrations`), so `all()` is only wired into the plugin behind the `rust-migrations` Cargo
//! feature. The embedding itself is unconditional and tested so flipping the feature is safe.

use tauri_plugin_sql::{Migration, MigrationKind};

/// One embedded migration file. Kept separate from the plugin type so the generated code does
/// not depend on the plugin's field layout.
pub struct EmbeddedMigration {
    pub version: i64,
    pub description: &'static str,
    pub sql: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

/// Database URL the frontend loads and that migrations are registered for. Must match
/// `plugins.sql.preload` in `tauri.conf.json` and `Database.load(...)` in `packages/db`.
pub const DB_URL: &str = "sqlite:epistemics.db";

pub fn all() -> Vec<Migration> {
    embedded()
        .into_iter()
        .map(|m| Migration { version: m.version, description: m.description, sql: m.sql, kind: MigrationKind::Up })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn migrations_are_dense_and_ascending() {
        let all = embedded();
        for (i, m) in all.iter().enumerate() {
            assert_eq!(m.version, i as i64 + 1, "migration {} has version {}", m.description, m.version);
            assert!(!m.sql.trim().is_empty(), "migration {} is empty", m.description);
        }
    }
}
