//! Schema migrations for the desktop SQLite database.
//!
//! The SQL is generated by drizzle-kit into `packages/db/migrations/*.sql` and embedded at build
//! time by `build.rs` (see `$OUT_DIR/migrations.rs`). Files are applied in name order and
//! numbered from 1; `tauri-plugin-sql` records applied versions in its own `_sqlx_migrations`
//! table, so the same file is never run twice.

use tauri_plugin_sql::{Migration, MigrationKind};

/// One embedded migration file. Kept separate from the plugin type so the generated code does
/// not depend on the plugin's field layout.
pub struct EmbeddedMigration {
    pub version: i64,
    pub description: &'static str,
    pub sql: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

/// Database URL the frontend loads and that migrations are registered for. Must match
/// `plugins.sql.preload` in `tauri.conf.json` and `Database.load(...)` in `packages/db`.
pub const DB_URL: &str = "sqlite:epistemics.db";

pub fn all() -> Vec<Migration> {
    embedded()
        .into_iter()
        .map(|m| Migration { version: m.version, description: m.description, sql: m.sql, kind: MigrationKind::Up })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn migrations_are_dense_and_ascending() {
        let all = embedded();
        for (i, m) in all.iter().enumerate() {
            assert_eq!(m.version, i as i64 + 1, "migration {} has version {}", m.description, m.version);
            assert!(!m.sql.trim().is_empty(), "migration {} is empty", m.description);
        }
    }
}
