#!/usr/bin/env node
/**
 * Regenerates src/prompts/*.ts from the human-readable prompt files in
 * content/prompts/architect-*.md. The markdown files are the source of truth;
 * the test suite asserts that both stay in sync.
 *
 *   node packages/architect/scripts/sync-prompts.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../..');
const STAGES = ['outline', 'concepts', 'graph', 'scripts', 'items', 'itemcheck'];

mkdirSync(resolve(here, '../src/prompts'), { recursive: true });
const versions = new Set();
for (const stage of STAGES) {
  const md = readFileSync(resolve(root, `content/prompts/architect-${stage}.md`), 'utf8');
  const m = /^<!--\s*version:\s*([\w.-]+)\s*-->\r?\n/.exec(md);
  if (!m) throw new Error(`architect-${stage}.md must start with a <!-- version: x.y --> header`);
  versions.add(m[1]);
  const body = md.slice(m[0].length).replace(/\r\n/g, '\n').trimEnd();
  const escaped = body.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  const name = stage.toUpperCase();
  const ts = `/* GENERATED by scripts/sync-prompts.mjs from content/prompts/architect-${stage}.md. Do not edit by hand. */\n\nexport const ${name}_PROMPT_VERSION = '${m[1]}';\n\nexport const ${name}_PROMPT = \`${escaped}\`;\n`;
  writeFileSync(resolve(here, `../src/prompts/${stage}.ts`), ts);
}
if (versions.size !== 1) throw new Error(`all architect prompts must share one version, got ${[...versions].join(', ')}`);
const idx = `/* GENERATED by scripts/sync-prompts.mjs. Do not edit by hand. */\n${STAGES.map((s) => `import { ${s.toUpperCase()}_PROMPT, ${s.toUpperCase()}_PROMPT_VERSION } from './${s}.js';`).join('\n')}\n\nexport { ${STAGES.map((s) => `${s.toUpperCase()}_PROMPT, ${s.toUpperCase()}_PROMPT_VERSION`).join(', ')} };\n\nexport type ArchitectStage = ${STAGES.map((s) => `'${s}'`).join(' | ')};\n\nexport const ARCHITECT_STAGES: readonly ArchitectStage[] = [${STAGES.map((s) => `'${s}'`).join(', ')}];\n\n/** All architect prompts share one version string (asserted by scripts/sync-prompts.mjs). */\nexport const ARCHITECT_PROMPT_VERSION = OUTLINE_PROMPT_VERSION;\n\nexport const ARCHITECT_PROMPTS: Record<ArchitectStage, string> = {\n${STAGES.map((s) => `  ${s}: ${s.toUpperCase()}_PROMPT,`).join('\n')}\n};\n`;
writeFileSync(resolve(here, '../src/prompts/index.ts'), idx);
console.log(`synced ${STAGES.length} prompts (version ${[...versions][0]})`);
