//! Standard Tauri build script plus migration embedding.
//!
//! Every `packages/db/migrations/*.sql` file (drizzle-kit output, sorted by name) becomes an
//! entry in `$OUT_DIR/migrations.rs`, which `src/migrations.rs` includes. Regenerated whenever
//! the directory changes, so adding a migration on the TypeScript side is picked up by the next
//! `cargo build` with no manual list to maintain.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    embed_migrations();
    tauri_build::build();
}

fn embed_migrations() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    // `EPISTEMICS_MIGRATIONS_DIR` overrides the default location (used by CI and scratch builds).
    println!("cargo:rerun-if-env-changed=EPISTEMICS_MIGRATIONS_DIR");
    let migrations_dir = env::var_os("EPISTEMICS_MIGRATIONS_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| manifest_dir.join("../../../packages/db/migrations"));
    let migrations_dir = migrations_dir.canonicalize().unwrap_or(migrations_dir);

    println!("cargo:rerun-if-changed={}", migrations_dir.display());

    let mut files: Vec<PathBuf> = match fs::read_dir(&migrations_dir) {
        Ok(entries) => entries
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.extension().map(|x| x == "sql").unwrap_or(false))
            .collect(),
        Err(_) => {
            println!(
                "cargo:warning=migrations directory not found at {}; the app will start with an empty schema",
                migrations_dir.display()
            );
            Vec::new()
        }
    };
    files.sort();

    let mut out = String::new();
    out.push_str("// @generated by build.rs from packages/db/migrations/*.sql\n");
    out.push_str("pub fn embedded() -> Vec<EmbeddedMigration> {\n    vec![\n");
    for (i, path) in files.iter().enumerate() {
        println!("cargo:rerun-if-changed={}", path.display());
        let file_name = path.file_name().unwrap().to_string_lossy().to_string();
        let description = describe(&file_name);
        out.push_str(&format!(
            "        EmbeddedMigration {{ version: {version}, description: {desc:?}, sql: include_str!({path:?}) }},\n",
            version = (i as i64) + 1,
            desc = description,
            path = path.display().to_string(),
        ));
    }
    out.push_str("    ]\n}\n");

    fs::write(out_dir.join("migrations.rs"), out).expect("write migrations.rs");
}

/// `0003_brave_wolverine.sql` -> `brave_wolverine`; falls back to the stem.
fn describe(file_name: &str) -> String {
    let stem = Path::new(file_name).file_stem().map(|s| s.to_string_lossy().to_string()).unwrap_or_default();
    match stem.split_once('_') {
        Some((prefix, rest)) if prefix.chars().all(|c| c.is_ascii_digit()) && !rest.is_empty() => rest.to_string(),
        _ => stem,
    }
}
