/**
 * Reads migrations/*.sql (drizzle-kit output, ordered by the numeric prefix / journal) and rewrites
 * src/migrations.ts so executors can apply them without filesystem access.
 * Run: node --experimental-strip-types scripts/embed-migrations.ts
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'migrations');
const journalPath = join(dir, 'meta', '_journal.json');

let names: string[];
if (existsSync(journalPath)) {
  const journal = JSON.parse(readFileSync(journalPath, 'utf8')) as { entries: { tag: string }[] };
  names = journal.entries.map((e) => e.tag);
} else {
  names = readdirSync(dir).filter((f) => f.endsWith('.sql')).map((f) => f.replace(/\.sql$/, '')).sort();
}

const migrations = names.map((name) => ({ name, sql: readFileSync(join(dir, `${name}.sql`), 'utf8') }));

const out = `/**
 * GENERATED by scripts/embed-migrations.ts from migrations/*.sql — do not edit by hand.
 * Regenerate with \`pnpm --filter @epistemics/db generate\`.
 * Each executor applies these in order, keeping a \`_migrations(name TEXT PRIMARY KEY, applied_at INTEGER)\` table,
 * and splits each file on drizzle-kit's \`--> statement-breakpoint\` marker.
 */
export const MIGRATIONS: { name: string; sql: string }[] = ${JSON.stringify(migrations, null, 2)};
`;
writeFileSync(join(root, 'src', 'migrations.ts'), out);
console.log(`embedded ${migrations.length} migration(s): ${names.join(', ')}`);
