/* GENERATED by scripts/sync-prompts.mjs. Do not edit by hand. */
import { OUTLINE_PROMPT, OUTLINE_PROMPT_VERSION } from './outline.js';
import { CONCEPTS_PROMPT, CONCEPTS_PROMPT_VERSION } from './concepts.js';
import { GRAPH_PROMPT, GRAPH_PROMPT_VERSION } from './graph.js';
import { SCRIPTS_PROMPT, SCRIPTS_PROMPT_VERSION } from './scripts.js';
import { ITEMS_PROMPT, ITEMS_PROMPT_VERSION } from './items.js';
import { ITEMCHECK_PROMPT, ITEMCHECK_PROMPT_VERSION } from './itemcheck.js';

export { OUTLINE_PROMPT, OUTLINE_PROMPT_VERSION, CONCEPTS_PROMPT, CONCEPTS_PROMPT_VERSION, GRAPH_PROMPT, GRAPH_PROMPT_VERSION, SCRIPTS_PROMPT, SCRIPTS_PROMPT_VERSION, ITEMS_PROMPT, ITEMS_PROMPT_VERSION, ITEMCHECK_PROMPT, ITEMCHECK_PROMPT_VERSION };

export type ArchitectStage = 'outline' | 'concepts' | 'graph' | 'scripts' | 'items' | 'itemcheck';

export const ARCHITECT_STAGES: readonly ArchitectStage[] = ['outline', 'concepts', 'graph', 'scripts', 'items', 'itemcheck'];

/** All architect prompts share one version string (asserted by scripts/sync-prompts.mjs). */
export const ARCHITECT_PROMPT_VERSION = OUTLINE_PROMPT_VERSION;

export const ARCHITECT_PROMPTS: Record<ArchitectStage, string> = {
  outline: OUTLINE_PROMPT,
  concepts: CONCEPTS_PROMPT,
  graph: GRAPH_PROMPT,
  scripts: SCRIPTS_PROMPT,
  items: ITEMS_PROMPT,
  itemcheck: ITEMCHECK_PROMPT,
};
